# Simulation configuration
# Initial balance for each account in the simulation
# This is the amount of tokens each account starts with
initial_balance = 9999

# Number of accounts to create in the simulation
# These accounts will be used to send transactions between
num_accounts = 1000

# Target transactions per second to maintain during simulation
# The simulator will try to maintain this rate by adjusting delays
target_tps = 100.0

# Duration of the simulation in seconds
# The simulation will run for this many seconds
duration_seconds = 10

# Zipf distribution parameter for account selection
# Higher values (e.g., 1.5) make the distribution more skewed
# Lower values (e.g., 0.5) make the distribution more uniform
# Must be greater than 0
zipf_parameter = 1.0

# Ratio of transactions that will be CATs
ratio_cats = 0.1

# Block interval in seconds
block_interval = 0.1

# Number of blocks a CAT can be pending, before timing out
cat_lifetime = 5

# Chain configuration
[chains]
num_chains = 2
# Delay in seconds for each chain
# The order of delays corresponds to the chain order (chain-1, chain-2, etc.)
delays = [0.0, 0.0]  # chain-1 has .. delay, chain-2 has .. delay
