pub mod account_selection;
pub mod zipf_account_selection;
pub mod run_simulation;
pub mod simulation_results;
pub mod network;
pub mod config;
pub mod logging;
pub mod testnodes;
pub mod interface;
pub mod scenarios;
pub mod stats;
pub mod simulation_registry;

pub use account_selection::AccountSelectionStats;
pub use zipf_account_selection::AccountSelector;
pub use run_simulation::run_simulation;
pub use simulation_results::SimulationResults;
pub use network::initialize_accounts;
pub use testnodes::*; 
pub use interface::{SimulatorInterface, SimulationType};
pub use scenarios::sim_simple::run_simple_simulation;
pub use scenarios::sim_sweep_cat_rate::run_sweep_cat_rate_simulation;
pub use scenarios::sim_sweep_zipf::run_sweep_zipf_simulation;
pub use scenarios::sim_sweep_chain_delay::run_sweep_chain_delay;
pub use scenarios::sim_sweep_total_block_number::run_sweep_total_block_number;
pub use scenarios::sim_sweep_cat_lifetime::run_sweep_cat_lifetime_simulation;
pub use scenarios::sim_sweep_block_interval_constant_block_delay::run_sweep_block_interval_constant_block_delay;
pub use scenarios::sim_sweep_block_interval_constant_time_delay::run_sweep_block_interval_constant_time_delay;
pub use scenarios::sim_sweep_cat_pending_dependencies::run_sweep_cat_pending_dependencies_simulation;
pub use scenarios::run_all_tests; 

// ============================================================================
// Flexible Sweep Configuration Macro
// ============================================================================

/// Macro that generates a complete sweep configuration setup for a simulation.
/// 
/// This macro eliminates boilerplate code by automatically generating:
/// - A sweep config struct with standard fields (network_config, account_config, transaction_config, sweep)
/// - Standard validation logic (common field validation, positive simulation count)
/// - SweepConfigTrait implementation for integration with the generic SweepRunner
/// - A load_config() function that reads and validates the TOML configuration file
/// 
/// # Parameters
/// 
/// * `$config_name` - The name of the config struct to generate (e.g., SweepCatRateConfig)
/// * `$toml_file` - The TOML configuration file name (e.g., "config_sweep_cat_rate.toml")
/// * `validate_sweep_specific` - A closure that implements sweep-specific validation logic
/// 
/// # Generated Code
/// 
/// For each macro call, this generates:
/// 1. A struct with standard sweep configuration fields
/// 2. ValidateConfig implementation with common validation + custom validation
/// 3. SweepConfigTrait implementation for generic sweep runner compatibility
/// 4. A load_config() function that reads the TOML file and validates it
/// 
/// # Usage Example
/// 
/// ```rust
/// define_sweep_config!(
///     SweepCatRateConfig,
///     "config_sweep_cat_rate.toml",
///     validate_sweep_specific = |self_: &Self| {
///         if self_.sweep.cat_rate_step.is_none() {
///             return Err(ConfigError::ValidationError("CAT rate step must be specified".into()));
///         }
///         Ok(())
///     }
/// );
/// ```
#[macro_export]
macro_rules! define_sweep_config {
    (
        $config_name:ident,
        $toml_file:expr,
        validate_sweep_specific = $validate_block:expr
    ) => {
        /// Sweep configuration struct generated by define_sweep_config! macro.
        /// Contains all the configuration needed to run a parameter sweep simulation.
        #[derive(Debug, serde::Deserialize, Clone)]
        pub struct $config_name {
            pub network_config: crate::config::NetworkConfig,
            pub account_config: crate::config::AccountConfig,
            pub transaction_config: crate::config::TransactionConfig,
            pub sweep: crate::config::SweepParameters,
        }

        /// Standard validation implementation for sweep configurations.
        /// Validates common fields and ensures positive simulation count.
        impl crate::config::ValidateConfig for $config_name {
            fn validate_common(&self) -> Result<(), crate::config::ConfigError> {
                crate::config::validate_common_fields(&self.account_config, &self.transaction_config, &self.network_config)?;
                if self.sweep.num_simulations == 0 {
                    return Err(crate::config::ConfigError::ValidationError("Number of simulations must be positive".into()));
                }
                Ok(())
            }
            /// Sweep-specific validation logic provided by the macro caller.
            /// This allows each sweep to define its own validation requirements.
            fn validate_sweep_specific(&self) -> Result<(), crate::config::ConfigError> {
                ($validate_block)(self)
            }
        }

        /// SweepConfigTrait implementation for integration with the generic SweepRunner.
        /// Provides access to configuration data in a type-agnostic way.
        impl crate::scenarios::sweep_runner::SweepConfigTrait for $config_name {
            fn as_any(&self) -> &dyn std::any::Any { self }
            fn get_num_simulations(&self) -> usize { self.sweep.num_simulations }
            fn get_network_config(&self) -> &crate::config::NetworkConfig { &self.network_config }
            fn get_account_config(&self) -> &crate::config::AccountConfig { &self.account_config }
            fn get_transaction_config(&self) -> &crate::config::TransactionConfig { &self.transaction_config }
        }

        /// Loads and validates the sweep configuration from the TOML file.
        /// This function is generated for each sweep and handles file reading,
        /// deserialization, and validation according to the sweep's specific rules.
        fn load_config() -> Result<$config_name, crate::config::ConfigError> {
            use std::fs;
            use toml;
            let config_str = fs::read_to_string(concat!("simulator/src/scenarios/", $toml_file))?;
            let config: $config_name = toml::from_str(&config_str)?;
            config.validate()?;
            Ok(config)
        }
    };
} 