# Sweep CAT Pending Dependencies Simulation Configuration

# Network parameters
[network_config]
# the number of chains to simulate
num_chains = 2
# Delay in blocks for each chain
# The order of delays corresponds to the chain order (chain-1, chain-2, etc.)
chain_delays = [0, 5]  # chain-1 has 0 blocks delay, chain-2 has 5 blocks delay
# Block interval in seconds
block_interval = 0.02

# Account parameters
[account_config]
# Initial balance for each account in the simulation
# This is the amount of tokens each account starts with
initial_balance = 9999
# Number of accounts to create in the simulation
# These accounts will be used to send transactions between
num_accounts = 1000

# Transaction parameters
[transaction_config]
# Target transactions per second to maintain during simulation
# The simulator will try to maintain this rate by adjusting delays
target_tps = 500.0
# Total number of blocks to simulate
# The simulation will run until this many blocks have been produced
sim_total_block_number = 1000
# Zipf distribution parameter for account selection
# Higher values (e.g., 1.5) make the distribution more skewed
# Lower values (e.g., 0.5) make the distribution more uniform
# Must be greater than or equal to 0
zipf_parameter = 1.0
# Ratio of transactions that will be CATs
ratio_cats = 0.1
# CAT lifetime in blocks
# This is the maximum number of blocks a CAT transaction can remain pending
cat_lifetime_blocks = 10
# Number of blocks to wait before starting transaction submission
# This ensures the system is fully initialized and stable
initialization_wait_blocks = 10
# Number of blocks to wait for account funding to complete
# This ensures all accounts are properly funded before starting simulation
funding_wait_blocks = 10
# Whether to allow CAT transactions to depend on locked keys
# This value will be overridden by the sweep test (false and true)
allow_cat_pending_dependencies = false

# Sweep parameters
[sweep_config]
num_simulations = 2 # Number of simulations to run (false, true)

# Repeat parameters
[repeat_config]
# Number of times to run each simulation (results will be averaged)
num_runs = 20