# Simulation configuration for duration sweep

# Network parameters
[network]
# the number of chains to simulate
num_chains = 2
# Delay in seconds for each chain
# The order of delays corresponds to the chain order (chain-1, chain-2, etc.)
chain_delays = [0.0, 0.5]  # chain-1 has 0 delay, chain-2 has 0.5 delay
# Block interval in seconds
block_interval = 0.1

# Account parameters
[accounts]
# Initial balance for each account in the simulation
# This is the amount of tokens each account starts with
initial_balance = 9999
# Number of accounts to create in the simulation
# These accounts will be used to send transactions between
num_accounts = 1000

# Transaction parameters
[transactions]
# Target transactions per second to maintain during simulation
# The simulator will try to maintain this rate by adjusting delays
target_tps = 100.0
# Duration of the simulation in seconds
# The simulation will run for this many seconds
duration_seconds = 5
# Zipf distribution parameter for account selection
# Higher values (e.g., 1.5) make the distribution more skewed
# Lower values (e.g., 0.5) make the distribution more uniform
# Must be greater than or equal to 0
zipf_parameter = 1.0
# Ratio of transactions that will be CATs
ratio_cats = 0.1
# CAT lifetime in blocks
# This is the maximum number of blocks a CAT transaction can remain pending
cat_lifetime_blocks = 10
# Number of blocks to wait before starting transaction submission
# This ensures the system is fully initialized and stable
initialization_wait_blocks = 10

# Sweep parameters
[sweep]
num_simulations = 4 # Number of simulations to run (5s, 10s, 15s, 20s)
duration_step = 5 # Step size for duration parameter, starting from 5 